### ISSUE TITLE
Generates deprecation warning on Ember 2.1.0

### ISSUE THREAD

**Issue by amaqui** [kellyselden/ember-i18n-inject#1]
DEPRECATION: The `initialize` method for Application initializer 'ember-i18n' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments] See http://emberjs.com/deprecations/v2.x/#toc_initializer-arity for more details.

**Comment by kellyselden** [comment]
Thanks for reporting this. I will keep it on my radar.
