### ISSUE TITLE
Integration testing of components

### ISSUE THREAD

**Issue by sbsurf** [kellyselden/ember-i18n-inject#6]
Hi,

I am having trouble getting integration tests to pass without explicitly injecting the i18n service inside the component, which defeats the purpose of this add-on.

Can you please recommend a way to test so that the service gets injected properly?

**Comment by kellyselden** [comment]
These injections are for a running app, not integration tests. I'm assuming you are integration testing. Initializers are not run in component integration tests. See more here https://github.com/emberjs/ember.js/issues/12114
